version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: drone_db
    environment:
      POSTGRES_DB: drone_db
      POSTGRES_USER: drone_user
      POSTGRES_PASSWORD: drone_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 